// styles.ts
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f6fa', paddingTop: 60 },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, marginBottom: 20 },
  headerImage: { width: 45, height: 45, borderRadius: 22.5, marginRight: 12 },
  headerTitle: { fontSize: 26, fontWeight: 'bold', color: '#2f3640' },
  formContainer: { backgroundColor: '#ffffff', marginHorizontal: 20, padding: 15, borderRadius: 10, elevation: 3 },
  input: { borderWidth: 1, borderColor: '#dcdde1', borderRadius: 6, padding: 12, fontSize: 16, marginBottom: 12, color: '#2f3640' },
  prioritySelector: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  priorityBtn: { flex: 1, paddingVertical: 10, marginHorizontal: 4, borderWidth: 1, borderColor: '#dcdde1', borderRadius: 6, alignItems: 'center', backgroundColor: '#fff' },
  priorityBtnSelected: { backgroundColor: '#00a8ff', borderColor: '#00a8ff' },
  priorityBtnText: { color: '#718093', fontWeight: '600' },
  priorityBtnTextSelected: { color: '#fff' },
  submitButton: { backgroundColor: '#4cd137', paddingVertical: 12, borderRadius: 6, alignItems: 'center' },
  submitButtonText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  purgeButton: { backgroundColor: '#ee5253', marginHorizontal: 20, marginTop: 15, paddingVertical: 10, borderRadius: 6, alignItems: 'center' },
  purgeButtonText: { color: '#fff', fontWeight: 'bold' },
  listContainer: { paddingHorizontal: 20, paddingTop: 15 },
  taskCard: { backgroundColor: '#fff', padding: 15, borderRadius: 8, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10, borderLeftWidth: 5, borderLeftColor: '#718093', elevation: 1 },
  taskCompleted: { backgroundColor: '#f1f2f6', borderLeftColor: '#dcdde1' },
  taskInfo: { flex: 1, paddingRight: 10 },
  taskText: { fontSize: 16, color: '#2f3640', fontWeight: '500' },
  textLineThrough: { textDecorationLine: 'line-through', color: '#a4b0be' },
  priorityBadge: { alignSelf: 'flex-start', fontSize: 11, fontWeight: 'bold', color: '#fff', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 4, marginTop: 6 },
  priorityBaja: { backgroundColor: '#1dd1a1' },
  priorityMedia: { backgroundColor: '#feca57' },
  priorityAlta: { backgroundColor: '#ff6b6b' },
  actionsContainer: { flexDirection: 'row' },
  actionButton: { padding: 10, borderRadius: 6, marginLeft: 6, width: 40, height: 40, justifyContent: 'center', alignItems: 'center' },
  btnComplete: { backgroundColor: '#4cd137' },
  btnDelete: { backgroundColor: '#ee5253' },
  actionButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 14 },
  emptyText: { textAlign: 'center', color: '#a4b0be', marginTop: 40, fontSize: 16 },
});